### ISSUE TITLE
Redesign of the ids:Language class / properties using more accurate ontologies.

### ISSUE THREAD

**Issue by HaydarAk** [IndustrialDataSpace/InformationModel#134]
### Problem:
The current implementation of ids:Language, especially the language instances, lack references to existing, standardized language vocabularies and language code lists. dcterms is inaccurate. 

### Suggestion:
Redesign ids:Language using the [Lingvoj vocabulary](http://linkedvocabs.org/lingvoj/). Lingvoj further specifies dcterms:language and dcterms:LinguisticSystem and also contains instances of languages with references to standardized language codes. 

**Example of an instance**

```
lexvo:deu
    a   schema:Language, lingvo:Lingvo ;
    rdfs:label   "German" ; 
    lvont:iso639P1Code   "de" ;
    owl:sameAs  loc1:de ; 
    lvont:iso639P2BCode   "ger" ;
    owl:sameAs  loc2:ger ;
    lvont:iso639P2TCode   "deu" ;
    lvont:iso639P3Code   "deu" ; 
    owl:sameAs <http://dbpedia.org/resource/ISO_639:deu> ;
    rdfs:seeAlso <https://www.freebase.com/authority/iso/639_3/deu> ;
    prov:hadPrimarySource  <http://www-01.sil.org/iso639-3/documentation.asp?id=deu> ;
    lingvo:supportingResource  <http://www.language-archives.org/language/deu> ; 
    lingvo:supportingResource  <http://eurovoc.europa.eu/drupal/?q=de> ;
    lingvo:supportingResource  <http://www.eionet.europa.eu/gemet/index_html?langcode=de> ;
    lingvo:supportingResource  <http://de.wikipedia.org> ;                                                  
    lingvo:supportingResource  <http://en.wiktionary.org/wiki/Category:German_language> ;    
    lingvo:supportingResource  <http://www.freelang.net/dictionary/german.php> ; 
    lingvo:supportingResource  <http://www.omniglot.com/writing/german.htm> ; 
    lingvo:supportingResource  <http://www.lexilogos.com/english/german_dictionary> ; 
    lingvo:supportingResource  <http://www.lexicool.com/dictionaries_german.asp> ; 
    foaf:isPrimaryTopicOf   <http://www.lingvoj.org/languages/tag-de.html> .    

```

**Comment by sebbader** [comment]
I am not sure how 'durable' the vocabulary is. There is no organization behind it and I could be that at some point in the future the server and the vocab are simply gone. However, I really like the references to ISO 639. Can't we just link to that standard, and 'pretend' its RDF/Linked Data?

**Comment by HaydarAk** [comment]
> Can't we just link to that standard, and 'pretend' its RDF/Linked Data?
That's basically what they do with:
`owl:sameAs <http://dbpedia.org/resource/ISO_639:deu> ;`

except that they also define additional properties and related resources. 

### Possible solution
What would be the "best practice" modelling of this ? 
Adding the references to the of ids:Language instances (example below) ? 
```
idsc:GERMAN a ids:Language;
    rdfs:label "German";
    owl:sameAs <http://dbpedia.org/resource/ISO_639:deu> ;
```

We could also switch to the coding scheme of the ISO standard, for the code:
```
idsc:DEU a ids:Language;
    rdfs:label "German";
    owl:sameAs <http://dbpedia.org/resource/ISO_639:deu> ;
```
