### ISSUE TITLE
Some minor errors worth mentioning

### ISSUE THREAD

**Issue by spetrac-nicos-ag** [IndustrialDataSpace/InformationModel#135]
Just to mention two minor errors I have encountered in the info model:

1. Just a typo at `ids:Site rdfs:subclassOf org:Site`, should be `rdfs:subClassOf` with a capital C.
2. `idsm:abstract` is a DatatypeProperty and its domain is `owl:Class`. And then there is the `ids:variant` ObjectProperty which also uses `idsm:abstract`. In my understanding that might be invalid, because ObjectProperty is not `rdfs:subClassOf owl:Class` and therefore not be able to use the `idsm:abstract` which is defined to be used by `owl:Class` only.

Those errors are minor, but RDF graph interpreters might throw errors for inconsistency.

**Comment by sebbader** [comment]
Hi Simon, 

thanks for your remarks! Just did some adjustments. I'd say that both points were leftovers from previous changes. Can you let me know if that fixes it?

Best,
Sebastian

**Comment by spetrac-nicos-ag** [comment]
Yes, the spelling for `rdfs:subClassOf` is now fixed and the `idsm:abstract` property is now removed from `ids:variant`, which might also make more sense.
If I find anything else by accident, I will report back.

Thx, Simon
