### ISSUE TITLE
Usage Policies: Insert Time, Space, Organizations and Payment

### ISSUE THREAD

**Issue by sebbader** [IndustrialDataSpace/InformationModel#155]
The usage contracts need a basic vocabulary in order to talk about:

1. Time --> insert complete [owl-time](https://www.w3.org/TR/owl-time/)
2. Space = Geometric & spatial statements --> [GeoSPARQL](https://www.opengeospatial.org/standards/geosparql)?
3. Roles- and attribute-based access: --> [org ontology](https://www.w3.org/TR/vocab-org/)
4. basic business models (pay after x usages, freemium...) --> [Sankt Gallen Business Model Navigator](https://www.thegeniusworks.com/wp-content/uploads/2017/06/St-Gallen-Business-Model-Innovation-Paper.pdf)?

**Comment by jlangkau** [comment]
Hm.
1. very fine!
2. Yes, my same question: GeoSPARQL
3. x-access relates to org-ontology?!? How? Don't understand this...
4. no emotions.

**Comment by HaydarAk** [comment]
I agree on all of that. I'll take a look on that.


> 3. x-access relates to org-ontology?!? How? Don't understand this...
Havent looked into the org ontology in detail, but I think, @sebbader  suggests a more fine-grained modelling of ids:Participant / ids:Agent / ids:Person. 
Adding classes / properties for proper role modelling.

#### Usecase
I (data provider, company A) agree on a contract with company B and let them use my data but only for people with specific roles of company B.

Participant X is member of Sales Department of organisation B
Participant Y is member of Research Department of organisation B.

 I allow all "research department" members to use my data.
X cannot access data, but Y

**Comment by clange** [comment]
I agree that the org ontology (https://www.w3.org/TR/vocab-org/) should be suitable for modelling structures of organizations.

**Comment by sebbader** [comment]
done by #215
