### ISSUE TITLE
Connector SelfDescription: Specify available Agents

### ISSUE THREAD

**Issue by mkollenstart** [IndustrialDataSpace/InformationModel#163]
The Message structure allows specifying the senderAgent and recipientAgent. Which in my understanding allows for a participant to operate a connector that serves multiple participants.

For good discoverability and to verify whether or not a connector should use specific Agents in its messages, the connector SelfDescription should be able to include a list of Agents it handles (both sending and receiving). As this data would then be available in the Broker.

The use-case for this structure would be to allow small companies that cannot afford to operate a connector solely to team up and share a connector. Of course, this has implications on the trustworthiness of the connector/participants, but allows these participants to be interoperable in the IDS network.

**Comment by sebbader** [comment]
Very relevant topic. For now, I regarded the Connector acting "on behalf of" the distinct participant. That's not working for Connectors as a Service, right.
Currently, I see the ids:maintainer relation from a Connector to a Participant class. Does not cover your scenario of course. I think  we have two options:
a) use the existing ids:sovereign/ids:publisher relation on Resource-level, and infer the list of served Participants on the fly, or
b) explicitly add another list of participants, even though risking redundant information.

**Comment by sebbader** [comment]
In addition, the Participant Information Service also needs a list of known Participants. Currently, it's InfrastructureComponent but not a Connector. 
We should directly assign it to the Connector Class (which automatically also makes it an InfrastructureComponent) and add it a "participantList" relation. This one might also solve your issue, even though the interpretation woudl be slightly different:
Connector --participantList--> <some participants P> : I as a Connector serve Participant P (among others)
ParIS --participantList--> <some participants P>: I, as a ParIS, are aware of the following Participant P, and this is its metadata.

**Comment by maboeckmann** [comment]
> 
> 

> a) use the existing ids:sovereign/ids:publisher relation on Resource-level, and infer the list of served Participants on the fly, or

That list might be incomplete, if some participants who might be affiliated with a connector do not push any resources.

**Comment by mkollenstart** [comment]
> a) use the existing ids:sovereign/ids:publisher relation on Resource-level, and infer the list of served Participants on the fly, or

This option is for our use-case very interesting, as it directly scopes the agent list to specific endpoints. Also because the sovereign does not necessarily has to be an Participant, which might decrease potential administrative burdens on very small companies with one or 2 employees.

**Comment by HaydarAk** [comment]
After discussing this with @sebbader we came to the conclusion that:

> b) explicitly add another list of participants, even though risking redundant information.

is the better approach.  Although there is some redundancy in the list of Agents for a Connector and the publishers (_ids:publisher_) of a Connector in this approach, it leads to a more accurate and complete list of agents. We suggest to use one list for all available agents and not a "senderAgent" and "recipientAgent" list. The _roles_ of ids:Agents in a Connector are a Usage Control related topic. 

The first idea ( _a)_ ) would only list agents, which are already mentioned in the ids:publisher / ids:sovereign field of existing resources. This can cause problems if a Connector does not have any offered ids:Resources.

**Comment by HaydarAk** [comment]
see #164
