### ISSUE TITLE
Replace URL-encoded forward slash in mediatype instances by a readable character 

### ISSUE THREAD

**Issue by jpullmann** [IndustrialDataSpace/InformationModel#17]
Due to automated processing each single media type instance (InformationModel/modules/mediaType/IANAMediaType.ttl) contains a URL-encoded slash (%2F), example: ids_mt:application%2Fzlib. This should be replaced by a convenient, readable character, e.g. "_" resulting in "ids_mt:application_zlib".

**Comment by cmader** [comment]
fixed in pull request #18
