### ISSUE TITLE
Inconsistent cardinalities in metamodel vs. SHACL

### ISSUE THREAD

**Issue by clange** [IndustrialDataSpace/InformationModel#171]
At the IDSA Plugfest we just talked about examples for validating infomodel instances and/or how to generate valid instances from Java.

I chose ResourceShape as an example. It says "contractOffer minCount 1" (https://github.com/IndustrialDataSpace/InformationModel/blob/4ceeb45e705d904867f715957a1b32ecb88e4d1d/testing/content/ResourceShape.ttl#L69)

The metamodel validation metadata in Resource do not say so, i.e., there is no "NotNull" information (https://github.com/IndustrialDataSpace/InformationModel/blob/41697b44d4cc76f0d5e7ebca224e23307a79de8c/model/content/Resource.ttl#L28)

Which of the two is correct? If this is a mistake, does it also occur in other places?

**Comment by HaydarAk** [comment]
This is definitely an inconsistency and a mistake. The possible fix for this depends on how we define a Resource in the IDS. 

**Is a Contract Offer mandatory for a ids:Resource ?** 
- if no: we should remove the `sh:minCount 1 ;` from teh ids:ResourceShape
- if yes: we should add the  idsm:validation "NotNull" constraint to the ids:Resource

Both are plausible, but I'd say  it should **not** be mandatory.  One could publish a Resource without a Contract and update it afterwards.

**Comment by sebbader** [comment]
"Is a Contract Offer mandatory for a ids:Resource ?

    if no: we should remove the sh:minCount 1 ; from teh ids:ResourceShape"

+1 from my part. There must be a possibility to publish resources without licenses/contracts.

**Comment by HaydarAk** [comment]
fixed: see commit 5f3732f9668abf661ab9ef5b982a4e6a470a4825
