### ISSUE TITLE
SHACL IM Missmatch: Participant Email

### ISSUE THREAD

**Issue by maboeckmann** [IndustrialDataSpace/InformationModel#186]
For the Participant class, there is a missmatch between the SHACL shapes and the idsm:validation properties.
In the Information Model, we state that there can be multiple corporate email addresses:
https://github.com/IndustrialDataSpace/InformationModel/blob/develop/model/participant/Participant.ttl#L33

In SHACL, we state that there must be at least one corporate email address:
https://github.com/IndustrialDataSpace/InformationModel/blob/develop/testing/participant/ParticipantShape.ttl#L43

I would assume that the idsm version is correct.

**Comment by HaydarAk** [comment]
I think so too.  The Information Model is correct here. 

Fixed in 744ac612c559df4730c2420e0c5681da0af342c0 .
