### ISSUE TITLE
Class "Site" irrelevant?

### ISSUE THREAD

**Issue by maboeckmann** [IndustrialDataSpace/InformationModel#202]
In this information model, there is a class called Site used for modelling websites. It has exactly one property: ids:siteAddress (string).
However, the homepage and the corporate homepage of a participant are Datatype Properties, pointing directly to xsd:anyURI and not using the Site class at all. The "primary site" property of a participant is an Object Property, pointing to a Site object.

As the Site class only stores an address (which should be a URI, not a string), I would suggest removing this class and making ids:primarySite point to anyURI instead.

See here: https://github.com/IndustrialDataSpace/InformationModel/blob/develop/model/participant/Participant.ttl#L55

**Comment by HaydarAk** [comment]
I think the naming is a bit confusing.  I assume `ids:Site` should be used for a Participants address, e.g., office address of a company. See the corresponding documentation for [org:Site](https://www.w3.org/TR/vocab-org/#org:Site), which is a superclass of `ids:Site`. 

An enhancement could be a more fine-grained approach to model an address. Therefore rdfs:range of ìds:siteAddress` could for example reference the [v-card ontology](https://www.w3.org/TR/vcard-rdf/), but I'm ok with range xsd:string for now.

A RDF example in Turtle pseudocode, how the class should be used (in my understanding)

```
fraunhofer_foo a ids:Participant
    ids:corperateEmailAddress   _"info@foo.fraunhofer.de"_ (string)
    ids:corporateHomepage`  _"http://foo.fraunhofer.de"_ (URI)
    ids:primarySite [ a ids:Site
        ids:siteAdress    "Fraunhofer Foo 
                           Street 1
                           12345 Town
                           Germany"
                                ]
```

**Comment by maboeckmann** [comment]
Ahh, thanks for clarification. My bad :)
