### ISSUE TITLE
release v1.0.0

### ISSUE THREAD

**Issue by seebi** [IndustrialDataSpace/InformationModel#31]
- [x] build artifacts
- [x] validate build artifact in Corporate Memory
- [x] count triples
- [x] announce ids prefix at prefix.cc
- [x] upload artifact to github
- [x] fix namespace resolution at [permaid](https://github.com/perma-id/w3id.org/tree/master/idsa) @cmader 
- [x] announce ids vocab at LOV @jpullmann

**Comment by cmader** [comment]
So the proper redirect will be this one:

https://w3id.org/idsa -> 
https://github.com/IndustrialDataSpace/InformationModel/releases/download/v1.0.0/IDS-InformationModel_v1.0.0.ttl

correct?

**Comment by seebi** [comment]
The main vocabulary URL should result in this TTL link (https://w3id.org/idsa/core/).
Please also make sure that all concepts are redirected to this URL as well (such as https://w3id.org/idsa/core/ContentType )

**Comment by seebi** [comment]
PS: once you added the forwarding - I would like to validate it with my scripts

**Comment by cmader** [comment]
created the pull request to w3id with the new rewrite rule. seems to take some while until the redirect is effective.

**Comment by cmader** [comment]
Can be considered done
