### ISSUE TITLE
Create an IM documentation (e.g. as a GitHub page)

### ISSUE THREAD

**Issue by jpullmann** [IndustrialDataSpace/InformationModel#77]
Set-up a documentation generating pipeline, e.g. based on [Widoco](https://github.com/dgarijo/Widoco)

**Comment by sebbader** [comment]
New version updated, see https://sebbader.github.io/InformationModel/

**Comment by sebbader** [comment]
Done, see https://industrialdataspace.github.io/InformationModel/
For now, the gh-pages branch is used even though the website sources are in develop branch, too. Point is that develop is not a valid branch for github pages but only master or gh-pages. As soon as the next release merges the docs dir into master, the pages reference needs to point to <master>/docs .
