### ISSUE TITLE
Enhance description property for external vocabs

### ISSUE THREAD

**Issue by sebbader** [IndustrialDataSpace/InformationModel#89]
ids:Described (super class of ids:Resource) has the property ids:description. As far as I understand it, that's the best entry point for any explanation on the actual content of a resource.
However, ids:description has [range PlainLiteral](https://github.com/IndustrialDataSpace/InformationModel/blob/76f416f12f33e5d4fce26843f375663eff6f53cc/model/shared/Described.ttl#L43). In case I want to supply structured information (e.g. using other RDF ontologies), I am stuck here. 
In case we do not have a better construct to append such vocabs I suggest to change the range to rdf:Resource and provide best practices how to add both textual and machine-readable descriptions.

**Comment by mkollenstart** [comment]
I really like this proposed enhancement, as it is something we currently stumble upon.

I’m not quite sure if the ids:description property is the best field, as we like to introduce new properties that are not an description per se. Also that will make it more complex to write descriptions for all entities of the information model, making it possibly (depending on the Java representation) harder to understand for developers.

My suggestion would be to introduce an new optional field to ids:Described with a field like ids:additionalProperties or ids:extension to ids:Described.


In our use-cases we often have a need for simple extensions, like a key-value map with specific domain or sector properties.

**Comment by sebbader** [comment]
We need an example for our intended pattern for 2.0.0. @HaydarAk can you add one? For instance with an DBpedia entitiy.

**Comment by Madmatti** [comment]
It appears that we can do this via ids:theme, see: https://github.com/IndustrialDataSpace/InformationModel/blob/fb494ba2513f6799262751abe2d44b57507090b3/model/content/DigitalContent.ttl#L106
Issue seems to be resolved.
