### ISSUE TITLE
Arbitrary data in the IM

### ISSUE THREAD

**Issue by spetrac-nicos-ag** [IndustrialDataSpace/InformationModel#99]
At **/model/participant/references/foaf-20140412.ttl** I found a disturbing line that makes no sense to me:
`rdfs:Class a owl:Class .`
As far as I know (and from [https://www.w3.org/2002/07/owl#](https://www.w3.org/2002/07/owl#)), the owl:Class is a rdfs:Class and a subclass of rdfs:Class, but not the other way round. Also makes no sense if you think about it. That also implies, that foaf:Agent has an unneccesary rdf:type relation to rdfs:Class, because foaf:Agent is also a owl:Class.
It makes me wonder, if that reference document is trustworthy at all.

Edit:
At [http://xmlns.com/foaf/spec/20140114.rdf](http://xmlns.com/foaf/spec/20140114.rdf) you can find the current definition of foaf:Agent. There is no direct inheritance from rdfs:Class as you can see:
```xml
<rdfs:Class rdf:about="http://xmlns.com/foaf/0.1/Agent" vs:term_status="stable" rdfs:label="Agent" rdfs:comment="An agent (eg. person, group, software or physical artifact).">
  <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
  <owl:equivalentClass rdf:resource="http://purl.org/dc/terms/Agent"/>
</rdfs:Class>
```

**Comment by Madmatti** [comment]
Well spotted! Please note that these references are more for completeness sake than anything else.
I have recreated the document by using an open-source tool for converting the original JSON-LD format to turtle, see https://github.com/IndustrialDataSpace/InformationModel/pull/105
